# Robot.
map_frame_id:                               odom
robot_base_frame_id:                        base_link
robot_pose_with_covariance_topic:           /covariance_publisher  # in rover_21_localization
robot_pose_cache_size:                      200
point_cloud_topic:                          /lio_sam/mapping/map_local #/lio_sam/mapping/cloud_registered   #/cloud
track_point_frame_id:                       base_link
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0
min_update_rate:                            1.0
time_tolerance:                             1.0
time_offset_for_point_cloud:                0.0
sensor_processor/ignore_points_above:       1.0
robot_motion_map_update/covariance_scale:   0.01
sensor_frame_id: velodyne

# Sensor.
input_sources:                                                                  
  front:                                                                        
    type: pointcloud                                                            
    topic: /velodyne_points                                
    queue_size: 1                                
    publish_on_update: true                                                     
    sensor_processor:                                                           
      type: laser                                                               
      #ignore_points_above: 3                                              
      #ignore_points_below: -4.0                                                
      min_radius: 0.018                                                         
      beam_angle: 0.0006                                                        
      beam_constant: 0.0015

# Map.
length_in_x:                                62.0
length_in_y:                                62.0
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.35
min_variance:                               0.00009                                                              
max_variance:                               0.01                                                                 
mahalanobis_distance_threshold:             2.5                                              
multi_height_noise:                         0.00002
surface_normal_positive_axis:               z
fused_map_publishing_rate:                  0.1
enable_visibility_cleanup:                  false
visibility_cleanup_rate:                    1.0
scanning_duration:                          1.0
map_size:                                   1000

# Init submap
initialize_elevation_map:                   false
initialization_method:                      0
length_in_x_init_submap:                    1.0
length_in_y_init_submap:                    1.0
margin_init_submap:                         0.3
init_submap_height_offset:                  0.01
target_frame_init_submap:                   base_link
