submap_service: "/elevation_mapping/get_submap"
map_frame_id: "odom"     # Must be the same as the input elevation submap.
robot_frame_id: "base_link"
target_frame: "odom"
min_update_rate: 3
map_center_x: 0.0
map_center_y: 0.0
map_length_x: 62.0
map_length_y: 62.0
footprint_yaw: 0.7854
max_gap_width: 0.3
grid_map_to_initialize_traversability_map:
  enable: false
  grid_map_topic_name: initial_elevation_map
